# Generated by Django 4.2 on 2024-10-03 03:21

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Improntas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', django_mysql.models.EnumField(choices=[('original', 'Original'), ('regrabado', 'Regrabado'), ('grabado', 'Grabado'), ('no_aplica', 'No Aplica')])),
                ('fotos', models.ImageField(upload_to='fotos/')),
                ('observaciones', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PMC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('n_cilindro', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PMV',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_improntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_servicio.improntas')),
                ('id_novedades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_servicio.novedades')),
                ('id_pmc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_servicio.pmc')),
                ('id_pmv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_servicio.pmv')),
            ],
        ),
    ]
