# Generated by Django 4.2 on 2024-09-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100, unique=True)),
                ('nit', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100, unique=True)),
                ('telefono', models.BigIntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'})),
                ('ciudad', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.IntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, unique=True)),
                ('correo', models.EmailField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('AD', 'Adminitrador'), ('PR', 'Perito'), ('RC', 'Recepcionista'), ('CA', 'Administardor Convenio'), ('CC', 'Consultor Convenio')], max_length=2)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100)),
                ('ciudad', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100)),
                ('direccion', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100)),
                ('telefono', models.BigIntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'})),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.convenios')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.sucursales'),
        ),
    ]
