# Generated by Django 4.2 on 2024-09-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0002_alter_usuarios_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.empleados'),
        ),
    ]
