# Generated by Django 4.2 on 2024-10-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0003_alter_usuarios_id_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, unique=True)),
                ('correo', models.EmailField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no valido', 'max_length': 'Valor no fuera de los limites', 'unique': 'Este nombre de usuario  en uso.'}, max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('PR', 'Perito'), ('RC', 'Recepcionista'), ('CA', 'Administardor Convenio'), ('CC', 'Consultor Convenio')], max_length=2)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.empleado')),
            ],
        ),
        migrations.RenameModel(
            old_name='Convenios',
            new_name='Convenio',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_empleado',
        ),
        migrations.RenameModel(
            old_name='Sucursales',
            new_name='Sucursal',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.sucursal'),
        ),
    ]
