# Generated by Django 4.2 on 2024-10-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0006_alter_usuario_is_superuser_alter_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
