name: Update README

on:
  workflow_dispatch:   # permite ejecutarlo manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          echo "Edad: 30" > README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update age"
          git push
